apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmsmiddleware-deployment
  namespace: middleware
  labels:
    app: cmsmiddleware
spec:
  selector:
    matchLabels:
      app: cmsmiddleware
  replicas: 1
  template:
    metadata:
      labels:
        app: cmsmiddleware 
    spec:
      containers:
        - name: cmsmiddleware
          image: docker.io/library/cmsmw:v0.0.1
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: PORT
              value: "3001"
          command: 
            - "uvicorn"
          args: 
            - "main:app"
            - "--host"
            - "0.0.0.0"
            - "--port" 
            - "4001"

---

apiVersion: v1
kind: Service
metadata:
  name: cmsmiddleware-service
  namespace: middleware
  labels:
    app: cmsmiddleware
spec:
  selector:
    app: cmsmiddleware
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP

